### ISSUE TITLE
Wrong cmd example

### ISSUE THREAD

**Issue by Sciroccogti** [DivineWeiR/GymAutoOrderSEU#1]
The example of `orderByTime.js` is out of date:

https://github.com/DivineWeiR/GymAutoOrderSEU/blob/f92ea3699be5b957dafc6ec8ad52cab96ee16589/orderByTime.js#L38

Now it should be `"orderByTime.js -u 213200001 -p 123456 -d 2020-11-01 -t 6 -i 羽毛球"`

**Comment by DivineWeiR** [comment]
Done.
