### ISSUE TITLE
Can the project be used?

### ISSUE THREAD

**Issue by Crystal-Liu-resp** [DivineWeiR/GymAutoOrderSEU#2]
I found something wrong with the validate picture. 
Error: ENOENT: no such file or directory, open 'F:\GymAutoOrderSEU-main\validate.jpg'
And then I change the saved address and name of validate.jpg (it initially in the Validate folder and be saved as the name of validate${formData.username}.jpg), and it still can't work for the same reason as above. 
Fine, then I download a picture as an initial picture to deal with the problem, but the parsed picture always being the same as the initial picture(the picture is changed), and finally this picture format inexplicably has a problem, and can not be parsed, so the program is over. (I can't open the picture using the photo software as well.)

**Comment by DivineWeiR** [comment]
Solved. You can clone the new repo and try again.
